name: backend-go-test

on:
    push:
        branches:
            - "*"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.26.x'
            
            - name: Install dependencies
              working-directory: ./apps/backend
              run: go mod tidy
            
            - name: Run tests
              working-directory: ./apps/backend
              run: go test -v -covermode=atomic -coverpkg=./... -coverprofile=coverage.out ./...
            
            - name: Generate coverage report
              working-directory: ./apps/backend
              run: go tool cover -func=coverage.out && gocover-cobertura < coverage.out > coverage.xml
            
            - name: Upload coverage report
              uses: actions/upload-code-coverage@v1
              with:
                file: apps/backend/coverage.xml
                language: go
                label: Backend coverage
            